### ISSUE TITLE
Many errors...

### ISSUE THREAD

**Issue by dotMastaz** [visiblevc/wordpress-starter#43]
Hello,

I had many erros when docker-compose : 

ERROR: for db  driver failed programming external connectivity on endpoint theproject_db_1 (a74f76838da5608a454e97444153b2cb15bf79e8bf2250805140f1f25e0f33d6): Error starting userland proxy: listen tcp 0.0.0.0:3306: bind: address already in use
Traceback (most recent call last):
  File "/usr/local/container-station/python/bin/.libs/docker-compose", line 9, in <module>
    load_entry_point('docker-compose==1.7.1', 'console_scripts', 'docker-compose')()
  File "/share/CACHEDEV1_DATA/.qpkg/container-station/usr/local/container-station/python/lib/python2.7/site-packages/compose/cli/main.py", line 63, in main
    log.error(e.msg)
AttributeError: 'ProjectError' object has no attribute 'msg'
[/home/my/the-project] # docker-compose up
Creating theproject_db_1

ERROR: for db  driver failed programming external connectivity on endpoint theproject_db_1 (b98f59ebecb5c63f439d34c8a4b0475cdf380b26ca6b19a92f31927ff3701958): Error starting userland proxy: listen tcp 0.0.0.0:3306: bind: address already in use
Traceback (most recent call last):
  File "/usr/local/container-station/python/bin/.libs/docker-compose", line 9, in <module>
    load_entry_point('docker-compose==1.7.1', 'console_scripts', 'docker-compose')()
  File "/share/CACHEDEV1_DATA/.qpkg/container-station/usr/local/container-station/python/lib/python2.7/site-packages/compose/cli/main.py", line 63, in main
    log.error(e.msg)
AttributeError: 'ProjectError' object has no attribute 'msg'

ANY IDEAS ??!!
Thank you !

**Comment by dsifford** [comment]
Need context to be able to figure out what's going on.

Can you paste your compose file?

**Comment by dsifford** [comment]
@dotMastaz Any updates?

**Comment by karellm** [comment]
Closing for lack of activity. @dotMastaz Feel free to reopen with more details if the issue persists.
